name: mkdocs
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v1
      - name: Set up Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: 3.7
      - name: Install dependencies
          run: python -m pip install -e '.[docs]'
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}